version: 0.0
os: linux
files:
  # The source directory (e.g., build/) from CodeBuild
  - source: /
    destination: /home/ubuntu/my-app

hooks:
  # BeforeInstall - Clean the previous application if needed
  BeforeInstall:
    - location: scripts/clean_previous_build.sh  # Optional: Script to clean old files
      timeout: 180
      runas: root

  # AfterInstall - Perform any additional tasks such as installing dependencies
  AfterInstall:
    - location: scripts/install_dependencies.sh  # Optional: Install dependencies (like npm or node)
      timeout: 180
      runas: root

  # ApplicationStart - Start the Apache server or perform post-install tasks
  ApplicationStart:
    - location: scripts/start_nginx.sh  # Start Apache to serve the app
      timeout: 180
      runas: root

  # ApplicationStop - Stop the Apache server or clean up
  ApplicationStop:
    - location: scripts/stop_nginx.sh  # Stop Apache if it is running
      timeout: 180
      runas: root